server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: AssetLifecycleManagement
  profiles:
    include: local
# database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
# JPA
  jpa:
    hibernate:
      ddl-auto: validate  # Change from 'update' to 'validate' when using Flyway
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false
# flyway (db-update)
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
# caching
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5m,expireAfterAccess=3m
    redis:
      time-to-live: 1800000
      cache-null-values: false
# redis
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
# logging
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.flywaydb: DEBUG
# Swagger/OpenAPI Configuration
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  # Optional: Group configuration
  group-configs[0]:
    group: employee-api
    paths-to-match: /api/v1/employees/**
